# name of your github action
name: ElectronCI
# this will help you specify where to run 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: see directory
        run: ls

      - name: Install dependencies
        run: npm ci
          
      - name: Build Electron
        run: npm run build

      - name: see directory
        run: ls ./dist
        
      - uses: lucyio/upload-to-release@master
        with:
          name: lucyio/electron
          path: ./dist
          action: unpublished
          release_id: ${{ startsWith(github.ref, 'refs/tags/v') }}
          release-repo: lucyio/electron