name: Build/release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest # ${{ matrix.os }}

    # Platforms to build on/for
    # strategy:
    #   matrix:
    #     os: [windows-latest,  ubuntu-latest] #macos-latest, ubuntu-latest, 
    #     # node-version: [18.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js #${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x #${{ matrix.node-version }}
          cache: 'npm'

      - name: Install packages & Build
        run: |
          npm ci
          npm run build

      - name: Create Tag
        uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_prefix: "v"  
